name: Generate js from SVGs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout icons
        uses: actions/checkout@v3
      - name: Checkout generator
        uses: actions/checkout@v3
        with:
          repository: Perth-Artifactory/ha-icon-generator
          path: generator
          ref: v0.2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Generate new js file from icons
        run: |
          python3 generator/generate.py svg standards stnd
      - name: Cleanup generator
        run: |
          rm -rf generator/
      - name: Commit changes
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          message: 'Update icon js'
          default_author: github_actions